name: Update Configs

on:
  #schedule:
   # - cron: '*/30 * * * *' # اجرا هر 30 دقیقه
  workflow_dispatch:      # قابلیت اجرای دستی

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: |
          pip install requests beautifulsoup4

      - name: Run Scraper Script
        run: python main.py
        # حتما چک کنید اسم فایل پایتون در ریپوی شما main.py باشد
        # اگر اسمش چیز دیگری است (مثلا 113333.txt یا script.py) اینجا تغییرش دهید

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # مرحله حیاتی: اضافه کردن تمام فایل‌های جدید (مثل configs5)
          git add .
          
          # نمایش وضعیت فایل‌ها برای دیباگ
          git status
          
          # کامیت کردن تغییرات (اگر تغییری باشد)
          git diff --staged --quiet || (git commit -m "Auto Update Configs + configs5" && git push)
